version: '3.8'
services:
  api-pedido:
    image: fiap56soat1/fasteats-ms-pedido-api:latest
    restart: always
    environment:
      - DB_SERVER=mysql-pedido
      - DB_PORT=3306
      - DB_NAME=fasteatspedidodb
      - DB_USER=fiap56
      - DB_PASSWORD=fiapsoat1grupo56
      - DB_ROOT_PASSWORD=fiapsoat1grupo56
      - MERCADO_PAGO_EMAIL_EMPRESA=pagamento@lanchonete-fiap.com.br
      - MERCADO_PAGO_CREDENCIAL=TEST-2087963774082813-080820-ee2b9b80edbdecf3ea8453bb8c088bc7-64946408
      - MERCADO_PAGO_USERID=64946408
      - MERCADO_PAGO_TIPO_PAGAMENTO=pix
      - URL_PAGAMENTO_SERVICE=http://api-pagamento:8081
      - URL_COZINHA_PEDIDO_SERVICE=http://api-producao:8082
    ports:
      - "8080:8080"
    networks:
      - fast-eats-app
    depends_on:
      mysql-pedido:
        condition: service_healthy

  mysql-pedido:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=fasteatspedidodb
      - MYSQL_USER=fiap56
      - MYSQL_PASSWORD=fiapsoat1grupo56
      - MYSQL_ROOT_PASSWORD=fiapsoat1grupo56
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - fast-eats-app
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql-pedido", "-u", "${DB_USER}", "--password=${DB_PASSWORD}" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  api-pagamento:
    image: fiap56soat1/fasteats-ms-pagamento-api:latest
    restart: always
    environment:
      - APP_PORT=8081
      - DB_SERVER=mysql-pagamento
      - DB_PORT=3307
      - DB_NAME=fasteatspagamentodb
      - DB_USER=fiap56
      - DB_PASSWORD=fiapsoat1grupo56
      - DB_ROOT_PASSWORD=fiapsoat1grupo56
      - MERCADO_PAGO_EMAIL_EMPRESA=pagamento@lanchonete-fiap.com.br
      - MERCADO_PAGO_CREDENCIAL=TEST-2087963774082813-080820-ee2b9b80edbdecf3ea8453bb8c088bc7-64946408
      - MERCADO_PAGO_USERID=64946408
      - MERCADO_PAGO_TIPO_PAGAMENTO=pix
      - URL_PEDIDO_SERVICE=http://api-pedido:8080
      - URL_COZINHA_PEDIDO_SERVICE=http://api-producao:8082
    ports:
      - "8081:8081"
    networks:
      - fast-eats-app
    depends_on:
      mysql-pagamento:
        condition: service_healthy

  mysql-pagamento:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=fasteatspagamentodb
      - MYSQL_USER=fiap56
      - MYSQL_PASSWORD=fiapsoat1grupo56
      - MYSQL_ROOT_PASSWORD=fiapsoat1grupo56
      - MYSQL_TCP_PORT=3307
    ports:
      - "3307:3307"
    expose:
      - "3307"
    networks:
      - fast-eats-app
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql-pagamento", "-u", "${DB_USER}", "--password=${DB_PASSWORD}" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  api-producao:
    image: fiap56soat1/fasteats-ms-producao-api:latest
    restart: always
    environment:
      - APP_PORT=8082
      - DB_USERNAME=fiap56
      - DB_PASSWORD=fiapsoat1grupo56
      - DB_NAME=fasteatsproducaodb
      - DB_PORT=27017
      - DB_HOST=mongo-producao
      - URL_PEDIDO_SERVICE=http://api-pedido:8080
      - URL_PAGAMENTO_SERVICE=http://api-pagamento:8081
    ports:
      - "8082:8082"
    networks:
      - fast-eats-app
    depends_on:
      mongo-producao:
        condition: service_healthy

  mongo-producao:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fiap56
      - MONGO_INITDB_ROOT_PASSWORD=fiapsoat1grupo56
    ports:
      - "27017:27017"
    networks:
      - fast-eats-app
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

networks:
  fast-eats-app:
    driver: bridge