version: '3.8'
services:
  api-pedido:
    image: fiap56soat1/fasteats-ms-pedido-api:latest
    restart: always
    environment:
      - DB_SERVER=mysql-pedido
      - DB_PORT=3306
      - DB_NAME=fasteatspedidodb
      - DB_USER=fiap56
      - DB_PASSWORD=fiapsoat1grupo56
      - DB_ROOT_PASSWORD=fiapsoat1grupo56
      - MERCADO_PAGO_EMAIL_EMPRESA=pagamento@lanchonete-fiap.com.br
      - MERCADO_PAGO_CREDENCIAL=TEST-2087963774082813-080820-ee2b9b80edbdecf3ea8453bb8c088bc7-64946408
      - MERCADO_PAGO_USERID=64946408
      - MERCADO_PAGO_TIPO_PAGAMENTO=pix
      - URL_PAGAMENTO_SERVICE=http://api-pagamento:8081
      - URL_COZINHA_PEDIDO_SERVICE=http://api-producao:8082
      - ENCRYPTION_KEY=D3CB53F3-5D90-445A-85EC-BE30954708D2
      - AWS_ACCESS_KEY=TESTE
      - AWS_SECRET_KEY=TESTE/TESTE
      - AWS_SESSION_TOKEN=TESTETESTE
      - AWS_REGION=us-west-2
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - AWS_SQS_QUEUE_PEDIDO_CRIADO=pedido-criado
      - AWS_SQS_QUEUE_PEDIDO_AGUARDANDO_PAGAMENTO=pedido-aguardando-pagamento
      - AWS_SQS_QUEUE_PEDIDO_PAGO=pedido-pago
      - AWS_SQS_QUEUE_PEDIDO_RECEBIDO=pedido-recebido
      - AWS_SQS_QUEUE_PEDIDO_EM_PREPARO=pedido-em-preparo
      - AWS_SQS_QUEUE_PEDIDO_PRONTO=pedido-pronto
      - AWS_SQS_QUEUE_PEDIDO_FINALIZADO=pedido-finalizado
      - AWS_SQS_QUEUE_PEDIDO_CANCELADO=pedido-cancelado
      - AWS_SQS_QUEUE_COZINHA_ERRO_PEDIDO_RECEBIDO=cozinha-erro-pedido-recebido
      - AWS_SQS_QUEUE_COZINHA_ERRO_PEDIDO_EM_PREPARO=cozinha-erro-pedido-em-preparo
      - AWS_SQS_QUEUE_COZINHA_ERRO_PEDIDO_PRONTO=cozinha-erro-pedido-pronto
      - AWS_SQS_QUEUE_COZINHA_ERRO_PEDIDO_FINALIZADO=cozinha-erro-pedido-finalizado
      - AWS_SQS_QUEUE_PAGAMENTO_ERRO_PEDIDO_CANCELAR=pagamento-erro-pedido-cancelar
      - AWS_SQS_QUEUE_PAGAMENTO_RECEBER_PEDIDO_PAGO=pagamento-receber-pedido-pago
      - AWS_SQS_QUEUE_PAGAMENTO_GERAR_PAGAMENTO=pagamento-gerar-pagamento
      - AWS_SQS_QUEUE_PAGAMENTO_CANCELAR_PAGAMENTO=pagamento-cancelar-pagamento
      - AWS_SQS_QUEUE_PAGAMENTO_ERRO_PAGAMENTO_PEDIDO=pagamento-erro-pagamento-pedido
    ports:
      - "8080:8080"
    networks:
      - fast-eats-app
    depends_on:
      mysql-pedido:
        condition: service_healthy
      localstack:
        condition: service_healthy

  mysql-pedido:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=fasteatspedidodb
      - MYSQL_USER=fiap56
      - MYSQL_PASSWORD=fiapsoat1grupo56
      - MYSQL_ROOT_PASSWORD=fiapsoat1grupo56
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - fast-eats-app
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql-pedido", "-u", "${DB_USER}", "--password=${DB_PASSWORD}" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  api-pagamento:
    image: fiap56soat1/fasteats-ms-pagamento-api:latest
    restart: always
    environment:
      - APP_PORT=8081
      - DB_SERVER=mysql-pagamento
      - DB_PORT=3307
      - DB_NAME=fasteatspagamentodb
      - DB_USER=fiap56
      - DB_PASSWORD=fiapsoat1grupo56
      - DB_ROOT_PASSWORD=fiapsoat1grupo56
      - MERCADO_PAGO_EMAIL_EMPRESA=pagamento@lanchonete-fiap.com.br
      - MERCADO_PAGO_CREDENCIAL=TEST-2087963774082813-080820-ee2b9b80edbdecf3ea8453bb8c088bc7-64946408
      - MERCADO_PAGO_USERID=64946408
      - MERCADO_PAGO_TIPO_PAGAMENTO=pix
      - URL_PEDIDO_SERVICE=http://api-pedido:8080
      - FAST_EATS_CONTATO_EMAIL_PADRAO_PAGAMENTO_PEDIDO=soat1grupo56@fasteats.com
      - AWS_ACCESS_KEY=TESTE
      - AWS_SECRET_KEY=TESTE/TESTE
      - AWS_SESSION_TOKEN=TESTETESTE
      - AWS_REGION=us-west-2
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - AWS_SQS_QUEUE_PEDIDO_CRIADO=pedido-criado
      - AWS_SQS_QUEUE_PEDIDO_AGUARDANDO_PAGAMENTO=pedido-aguardando-pagamento
      - AWS_SQS_QUEUE_PEDIDO_PAGO=pedido-pago
      - AWS_SQS_QUEUE_PEDIDO_CANCELADO=pedido-cancelado
      - AWS_SQS_QUEUE_COZINHA_RECEBER_PEDIDO=cozinha-receber-pedido
      - AWS_SQS_QUEUE_COZINHA_ERRO_RECEBER_PEDIDO=cozinha-erro-receber-pedido
      - AWS_SQS_QUEUE_PAGAMENTO_GERAR_PAGAMENTO=pagamento-gerar-pagamento
      - AWS_SQS_QUEUE_PAGAMENTO_RECEBER_PEDIDO_PAGO=pagamento-receber-pedido-pago
      - AWS_SQS_QUEUE_NOTIFICAR_CLIENTE=notificar-cliente
      - AWS_SQS_QUEUE_PAGAMENTO_CANCELAR_PAGAMENTO=pagamento-cancelar-pagamento
      - AWS_SQS_QUEUE_PAGAMENTO_ERRO_PAGAMENTO_PEDIDO=pagamento-erro-pagamento-pedido
      - AWS_SQS_QUEUE_PAGAMENTO_ERRO_PEDIDO_CANCELAR=pagamento-erro-pedido-cancelar
    ports:
      - "8081:8081"
    networks:
      - fast-eats-app
    depends_on:
      mysql-pagamento:
        condition: service_healthy
      localstack:
        condition: service_healthy

  mysql-pagamento:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=fasteatspagamentodb
      - MYSQL_USER=fiap56
      - MYSQL_PASSWORD=fiapsoat1grupo56
      - MYSQL_ROOT_PASSWORD=fiapsoat1grupo56
      - MYSQL_TCP_PORT=3307
    ports:
      - "3307:3307"
    expose:
      - "3307"
    networks:
      - fast-eats-app
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql-pagamento", "-u", "${DB_USER}", "--password=${DB_PASSWORD}" ]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  api-producao:
    image: fiap56soat1/fasteats-ms-producao-api:latest
    restart: always
    environment:
      - APP_PORT=8082
      - DB_USERNAME=fiap56
      - DB_PASSWORD=fiapsoat1grupo56
      - DB_NAME=fasteatsproducaodb
      - DB_PORT=27017
      - DB_HOST=mongo-producao
      - URL_PEDIDO_SERVICE=http://api-pedido:8080
      - AWS_ACCESS_KEY=TESTE
      - AWS_SECRET_KEY=TESTE/TESTE
      - AWS_SESSION_TOKEN=TESTETESTE
      - AWS_REGION=us-west-2
      - AWS_SQS_ENDPOINT=http://localstack:4566
      - AWS_SQS_QUEUE_PEDIDO_RECEBIDO=pedido-recebido
      - AWS_SQS_QUEUE_PEDIDO_EM_PREPARO=pedido-em-preparo
      - AWS_SQS_QUEUE_PEDIDO_PRONTO=pedido-pronto
      - AWS_SQS_QUEUE_PEDIDO_FINALIZADO=pedido-finalizado
      - AWS_SQS_QUEUE_COZINHA_RECEBER_PEDIDO=cozinha-receber-pedido
      - AWS_SQS_QUEUE_COZINHA_ERRO_RECEBER_PEDIDO=cozinha-erro-receber-pedido
      - AWS_SQS_QUEUE_COZINHA_ERRO_PEDIDO_RECEBIDO=cozinha-erro-pedido-recebido
      - AWS_SQS_QUEUE_COZINHA_ERRO_PEDIDO_EM_PREPARO=cozinha-erro-pedido-em-preparo
      - AWS_SQS_QUEUE_COZINHA_ERRO_PEDIDO_PRONTO=cozinha-erro-pedido-pronto
      - AWS_SQS_QUEUE_COZINHA_ERRO_PEDIDO_FINALIZADO=cozinha-erro-pedido-finalizado
    ports:
      - "8082:8082"
    networks:
      - fast-eats-app
    depends_on:
      mongo-producao:
        condition: service_healthy
      localstack:
        condition: service_healthy

  mongo-producao:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=fiap56
      - MONGO_INITDB_ROOT_PASSWORD=fiapsoat1grupo56
    ports:
      - "27017:27017"
    networks:
      - fast-eats-app
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet

  localstack:
    image: localstack/localstack
    privileged: true
    ports:
      - "4566:4566"
    networks:
      - fast-eats-app
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=0
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    healthcheck:
      test: awslocal sns list-topics && awslocal sqs list-queues
      interval: 3s
      timeout: 10s
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  # Our one-off task with AWS-CLI
  create-resources:
    restart: "no"
    image: amazon/aws-cli:2.11.0
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    networks:
      - fast-eats-app
    entrypoint: [ "sh", "-c" ]
    command: [
      " aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name notificar-cliente"
    ]

networks:
  fast-eats-app:
    driver: bridge