version: "3.8"
services:
  api_service:
    image: "fiap56soat1/fasteats-api:latest"
    restart: always
    ports:
      - "8080:8080"
    networks:
      - fiap-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/fasteatsdb?allowPublicKeyRetrieval=true
      - spring.datasource.username=${DB_USER}
      - spring.datasource.password=${DB_PASSWORD}
      - spring.flyway.url=jdbc:mysql://mysqldb:3306/fasteatsdb
      - spring.flyway.user=${DB_USER}
      - spring.flyway.password=${DB_PASSWORD}
      - spring.flyway.baseline-on-migrate=true
      - spring.flyway.locations=classpath:db/migration
    volumes:
      - .m2:/root/.m2
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - fiap-net
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
networks:
  fiap-net:
